name: Realty One Triad
favicon: null
layout_spectrum: 0.98708
typography_spectrum: 0.74976
title: Realty One
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#ffffff'
    - '#000000'
    - '#711e0e'
    - '#cfcfcf'
    - '#979797'
  brandStrength: 0.875
  lightness: 0.75
  saturation: 0.4375
  rhythmicContrast: 0
purpose: []
