name: Realty One Triad
favicon: null
layout_spectrum: 0.20320629747584462
typography_spectrum: 0.12484396272338927
title: Realty One
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#ffffff'
    - '#000000'
    - '#711e0e'
    - '#cfcfcf'
    - '#979797'
  brandStrength: 0.875
  lightness: 0.0019425672944635153
  saturation: 0.44259328208863735
  rhythmicContrast: 0.2863918144721538
purpose: []
